version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:file:/data/posdb
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.h2.Driver
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_H2_CONSOLE_ENABLED=true
    volumes:
      - h2_data:/data
      - .m2:/root/.m2
      - ./src/main/resources/static/tex:/data/tex:rw
      - ./src/main/resources/static/fonts:/data/fonts:rw
      - ./src/main/resources/static/pdf:/data/pdf:rw
    restart: unless-stopped

  springlatex:
    container_name: springlatex
    build: latexnode
    ports:
      - "3001:3001"
    volumes:
      - ./src/main/resources/static/tex:/data/tex:rw
      - ./src/main/resources/static/fonts:/data/fonts:rw
      - ./src/main/resources/static/pdf:/data/pdf:rw
    working_dir: /usr/src/app
    # entrypoint: bash
    # tty: true
    # stdin_open: true

volumes:
  h2_data:
  .m2: