## Send Post
POST http://localhost:8080/api/products
Content-Type: application/json

{
  "name": "iPhone 20",
  "price": 12.345,
  "inStock": 200
}
##################
## Send DELETE
DELETE http://localhost:8080/api/products/6
Content-Type: application/json
##################
## Update request
PUT  http://localhost:8080/api/products/8
Content-Type: application/json

{
  "name": "iPhone 30",
  "price": 15.345,
  "inStock": 200
}
##################
## Get all request
GET http://localhost:8080/api/products

###################
## Get request
GET http://localhost:8080/api/products/5


###################
## Get paginated request
GET http://localhost:8080/api/products/1/3


###################
####### ORDER #####
###################
## Get request
GET http://localhost:8080/api/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbGkiLCJyb2xlcyI6WyJVU0VSIl0sImlhdCI6MTc1NzE0ODcyOCwiZXhwIjoxNzU3MTUyMzI4fQ.RQep1SBPcu1P_Y_zsCjPWJ3YI2HnzO_HB4_vSp2m9CE

###################
## Get paginated request
GET http://localhost:8080/api/orders/0/3

###################
## Send DELETE
DELETE http://localhost:8080/api/orders/1
Content-Type: application/json


###################
## Send Post
POST http://localhost:8080/api/orders
Content-Type: application/json

{
  "items": [
    {
      "productId": 1,
      "quantity": 5
    },
    {
      "productId": 2,
      "quantity": 10
    }
  ]
}

#############
## Send Put
PUT http://localhost:8080/api/orders/2
Content-Type: application/json

{
  "items": [
    {
      "productId": 1,
      "quantity": 5
    },
    {
      "productId": 2,
      "quantity": 10
    }
  ]
}

###################
## ORDER PRODUCT ##
###################
## Get request
GET http://localhost:8080/api/order-products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbGkiLCJyb2xlcyI6WyJVU0VSIl0sImlhdCI6MTc1NjkyNzMxNSwiZXhwIjoxNzU2OTMwOTE1fQ.Ixm6p9LWjgwT0Rrm5Hht92dP06c3dI5auq2cpoNw3Qo


##################
## Send DELETE
DELETE http://localhost:8080/api/order-products/order/3
Content-Type: application/json

###################
##### COMMAND #####
###################

###################
## Send Post
POST http://localhost:8080/command
Content-Type: application/json

{
  "id": 2,
  "command": "list"
}
    


{
    "userVerification": "preferred",
    "challenge": "KnXdT2HqJZ_leWd3lYfpXPTk4rs-_HoVxaNucbc7gq4",
    "rpId": "pos.softhem.net",
    "allowCredentials": [
        {
            "transports": [
                "internal"
            ],
            "type": "public-key",
            "id": "oNR6EsGOjCwnPBdtCfebfIjzp00"
        }
    ]
}

######################################
############### NODE #################
######################################


## Send Post
POST http://localhost:8082/generate
Content-Type: application/json

{
  "id": 9,
  "name": "iPhone 20",
  "price": 12.345,
  "inStock": 200
}


##############################

HEAD https://pos.softhem.net/pdf/invoice/4


##############################

HEAD https://pos.softhem.net/pdf/4